version: "3"
services:
  php-fpm_service:
    container_name: "php-fpm-container"
    build: ./docker/php-fpm
    volumes:
      - ./app:/app
    restart: always 

  nginx_service:
    container_name: "nginx-container"
    build: ./docker/nginx
    volumes:
      - ./app:/app
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    ports: 
      - "8080:80"
    restart: always
    tty: true
    links:
      - "php-fpm_service"